spring.application.name=scholarbot

# Enable H2 database running in memory
spring.datasource.url=jdbc:h2:mem:scholarbotdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Tells Hibernate to automatically build/update database tables matching your Java classes
spring.jpa.hibernate.ddl-auto=update

# Optional: Shows the behind-the-scenes SQL queries in your IDE console
spring.jpa.show-sql=true
